### PR TITLE
Add Spotify Streaming Support

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Change-type: minor

### CODE REVIEW

**Comment by chrisys** [comment]
@AlexProgrammerDE I use Spotify premium and can confirm this works beautifully! Awesome work, let's get it merged!

I need you to add the following to the bottom of the commit message to allow our CI to perform versioning: `Change-type: minor`. You can do this with `git commit --amend` then force push this branch to update the message.

Thanks for the contribution!

**Comment by chrisys** [comment]
@AlexProgrammerDE just noticing; you're editing the GitHub PR description, it needs to be added to the commit message.

**Comment by AlexProgrammerDE** [comment]
Wait please i am not at home. I will try it at home.

**Comment by AlexProgrammerDE** [comment]
It don't want to work because the Airplay in the docker compose. I will try it with a new Pull request.

**Comment by AlexProgrammerDE** [comment]
@chrisys finished.

**Comment by AlexProgrammerDE** [comment]
Is it okay when i try it again with a new PR?

**Comment by AlexProgrammerDE** [comment]
I will try it with a new PR

**Pull request closed without merging**
