### PR TITLE
Allow setting custom name

### PR DESCRIPTION
**Pull request by roman-mazur**
It allows customizing how device is discovered with a simple docker-compose file change.

Change-type: patch
Signed-off-by: Roman Mazur <roman@balena.io>

### CODE REVIEW

**Comment by chrisys** [comment]
Yup definitely +1 from me on making it configurable via variables in the dashboard, and the rename makes sense too.

**Comment by zrzka** [comment]
It should work with the dashboard without any other change. But I forget about one thing, we can't use `BALENA_` prefix, because of this warning:

> Variables beginning RESIN_, BALENA_ configure balenaOS features. They must be named as per the documentation and managed on the Configuration page.

We should use different name. Like `BLUETOOTH_DEVICE_NAME`.

@roman-mazur ^^ can you please update this PR with:

* `BSHOSTNAME` -> `BLUETOOTH_DEVICE_NAME `
* Update README with a note that the default device name (`balenaSound xxxx`) can be changed via `BLUETOOTH_DEVICE_NAME ` environment variable (dashboard -> app -> device -> device variables)

Screenshot 2019-07-05 at 10 31 24

**Comment by roman-mazur** [comment]
@chrisys @zrzka 
Updated.

That said, I will be able to do an end-to-end test with the device a bit later today.

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by zrzka** [comment]
@roman-mazur please, update the screenshot with another one. I mean, I made it mainly for you with a completely different app (`camera-player`, device name `helen-player`). It looks weird when it's in the balena-sound repo :) Otherwise looks good! Thanks for making it! Once updated, feel free to merge.

**Comment by roman-mazur** [comment]
@zrzka ah, I didn't notice it was for a different app - will do, thanks

**Comment by roman-mazur** [comment]
Screenshot updated.
@balena-ci retest please

**Comment by roman-mazur** [comment]
@balena-ci retest please

Just checked on a device and rebased on master. It works.

**Pull request merged**
