### PR TITLE
Set the system volume to provided value in bluetooth-udev

### PR DESCRIPTION
**Pull request by barhun**
This one fixes a minor bug in bluetooth-udev which sets the system volume to 100% all the time and always.

### CODE REVIEW

**Comment by chrisys** [comment]
@barhun you almost got it, apart from the `Change-type` line should be in the body of the commit message, last, on a line of its own. You've put it in the header.

Additionally, for this particular change, it should be `Change-type: patch` as you're fixing a bug rather than adding a new feature.

If from your CLI you run `git commit --amend` you can edit the message and then push again with `--force` and it will update.

**Comment by barhun** [comment]
Thanks, it should be O.K. now. (:

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@barhun thanks for working on this! We're just trying to figure out why the CI is still failing; could you try adding a blank newline in your commit message before `Change-type: patch`?

Currently you have:
```
Set the system volume to provided value in bluetooth-udev
Change-type: patch
```

Can you try:
```
Set the system volume to provided value in bluetooth-udev

Change-type: patch
```

You can use amend in the same way as you did a moment ago.

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@barhun great stuff, thanks again for the contribution! 👍

**Comment by barhun** [comment]
You're all welcome. (: Sorry for causing a bit of trouble, it was my first contribution to your repos.

**Pull request merged**
