### PR TITLE
Add Audio Visualizing [help wanted]

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Change-type: major
Connects-to: #67 

Hi i am implementing in this PR a way to visualize audio. I am at the moment **NOT** finished and need to add some things. I am implementing the repo from balena-io-playground: https://github.com/balena-io-playground/x11-window-manager . You can check my work in this to-do list:

- [x] Add a desktop (X11)
- [x] Add RPI 4 support
- [ ] Find a desktop audio visualizer and implement it (I am trying at the moment glava: https://github.com/jarcode-foss/glava)
- [ ] Add improvements and work on stability

I will add in the future some commits and merge all at the end to one single commit.

bugs:

**help wanted**:
- [ ] glava build is failing
- [ ] is it building on the RPI 4?

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
Thanks @tmigone . Back to your question. I have two questions:

1. How can i detect/play music across container?

2. Is there a way to install obs in a container?

**Comment by AlexProgrammerDE** [comment]
Hi @tmigone . I could need your help. I do not know how to start glava as a window after the boot.
My secound problem is that meson lets me not configure the build. I had to create a fork and then to delete the obs part of the build file. I runned meson configure and it said that there is no build dir.

**Comment by chrisys** [comment]
@AlexProgrammerDE we need to be mindful here - do you think adding visualisations (although very cool) fits with the aim of the project to create a super simple audio streamer? We want to make sure it doesn't bloat the project too much with a feature that very few people use. What are your thoughts?

**Comment by AlexProgrammerDE** [comment]
@chrisys you are right with that. Not everyone has a display. This project aims to be placed behind a sound system. It could bloat the project. Maybe is this a cool idea for another project. 😄

**Pull request closed without merging**
