### PR TITLE
Set up PIN code with an environment variable

### PR DESCRIPTION
**Pull request by barhun**
Solves #34.

### CODE REVIEW

**Comment by chrisys** [comment]
@barhun what devices have you tested this to be working on? It doesn't look like you've implemented any authentication - my tests work as normal with no pairing code required.

**Comment by AlexProgrammerDE** [comment]
@chrisys have you tried to set the PIN code environment variable? Maybe no authentication is required when you haven't set the variable. He just added a variable option. He maked 
> return "0000"

to

> return os.getenv("BLUETOOTH_PIN_CODE", "0000")

and 

> return dbus.UInt32("0000")

to

> return dbus.UInt32(os.getenv("BLUETOOTH_PIN_CODE", "0000"))

I think if the pin code is not set it is 0000 and this means no authentication is required.
I hope i helped you. :wink:

**Comment by AlexProgrammerDE** [comment]
@chrisys I searched os.getenv and found this helpful page: https://www.geeksforgeeks.org/python-os-getenv-method/ . Summarized it says that when BLUETOOTH_PIN_CODE is not set it says 0000 but when as example BLUETOOTH_PIN_CODE is 1234 it says 1234 as output. So it should work what he wrote.

**Comment by barhun** [comment]
@chrisys I've got a Raspberry Pi 2 Model B with a USB Bluetooth adapter, and all the devices I've tried to paired with it asked me for a PIN code. Unless I type in `0000`, all pairing attempts get rejected. Isn't this behaviour other users are experiencing?

**Comment by barhun** [comment]
@AlexProgrammerDE yeah, what I did doesn't change the default behavior; but in my case, `0000` doesn't mean no authentication, I am required to type in that PIN to complete the pairing process.

**Comment by AlexProgrammerDE** [comment]
This is weird. I had one time the chance to test it on a Pi 3B and i didn't needed on this Pi a code I just needed to click on it and it will without 0000 pair.

**Comment by AlexProgrammerDE** [comment]
Maybe it didnt work properly on a Pi 2

**Comment by barhun** [comment]
Well, actually the USB adapter I use with my Pi 2 Model B supports only Bluetooth 2.1 + EDR and, unlike your case with Pi 3 Model B, it may not have support for bypassing the [Bluetooth Legacy PIN Code](https://www.google.com/search?q=Bluetooth+Legacy+PIN+Code). Some client devices even send this PIN beforehand without asking the user first; so, @AlexProgrammerDE, you must be right saying this is why you've never been asked for it. If you set a different PIN code via the environment variable `BLUETOOTH_PIN_CODE` , devices won't be able to bypass authentication and will ask you to enter the PIN code.

**Comment by barhun** [comment]
Could anyone with a Raspberry Pi 3 or any other model with built-in Bluetooth, please, test this by setting the environment variable?

**Comment by barhun** [comment]
Could anyone having a Raspberry Pi 3 or any other model with built-in Bluetooth, please, test this by setting the environment variable?

**Comment by AlexProgrammerDE** [comment]
Maybe can this page help you: https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/agent-api.txt
The first thing that should be done is that NoInputNooutput should be chanfed.
Read The Dbus api part please.

**Comment by chrisys** [comment]
@barhun I've tested this on a Pi Zero, Pi 3B+ and Pi 4B with the environment variable set - none of these devices prompt for the pin code. Thanks for working on figuring this out, the contribution is very much appreciated! If you need me to test anything else I am happy to.

**Comment by AlexProgrammerDE** [comment]
@chrisys could you test please my agent which i created in my fork: https://github.com/AlexProgrammerDE/balena-sound ?

**Comment by barhun** [comment]
Sooo, is it only me who has seen this `RequestPinCode` in device and service logs? 😝

image

**Comment by AlexProgrammerDE** [comment]
Was this on your Pi 2?

**Comment by barhun** [comment]
@AlexProgrammerDE Yep!

**Comment by AlexProgrammerDE** [comment]
I cant see. Is it mine or is it yours?

**Comment by AlexProgrammerDE** [comment]
I cant see. Is it mine or is it yours?

**Comment by barhun** [comment]
This is the master branch of [balena-io-projects/balena-sound](https://github.com/balena-io-projects/balena-sound/) deployed to my Raspberry Pi 2 with a USB Bluetooth adapter.

**Comment by AlexProgrammerDE** [comment]
This is:

    @dbus.service.method(AGENT_INTERFACE, in_signature="o", out_signature="s")
    def RequestPinCode(self, device):
        print("RequestPinCode (%s)" % (device))
        set_trusted(device)
        return "0000"

    @dbus.service.method(AGENT_INTERFACE, in_signature="o", out_signature="u")
    def RequestPasskey(self, device):
        print("RequestPasskey (%s)" % (device))
        set_trusted(device)
        return dbus.UInt32("0000")
But this runs usually not, but i dont know why.

**Comment by AlexProgrammerDE** [comment]
@barhun this is very weird. Your Pi is doing things not right. The variable is capability = "NoInputNoOutput". If you read https://www.kynetics.com/docs/2018/pairing_agents_bluez/ you know summarized (This is from there):

In particular, Agent's capability indicates how the authentication of two devices during the pairing process must be confirmed. Due to the nature and variety of Bluetooth devices, the value for capability can be:

    DisplayOnly or DisplayYesNo : authentication by PIN/passkey code
    KeyboardOnly or KeyboardDisplay : yes/no choice to the pairing attempt
    NoInputNoOutput : no user confirmation

**Comment by AlexProgrammerDE** [comment]
@barhun @chrisys can each of you please test my agent? I worked on it and i hope it works for each one of you. Bluez has created a Bluetooth agent in python at: https://github.com/pauloborges/bluez/blob/master/test/simple-agent . It is configurable and i hope it is working. If my agent is not working on the Pi 3 of chrisys we need to work on this agent in the future because it is the base of the actual agent in the master branch of this project. You will find the by me replaced bluetooth-agent file in my fork at: https://github.com/AlexProgrammerDE/balena-sound . Just build it.

**Comment by barhun** [comment]
@AlexProgrammerDE Hey, first of all, thanks for providing the links above that are full of useful information! I've just tested your agent, and needed to fix some parts of your code while doing so.

- remove `import bluezutils` on `line 13`. This leads to an import exception and isn't used anywhere.

- add `manager.RequestDefaultAgent(path)` on `line 149`. Without this, your methods will never be called.

- replace `ask("Enter PIN Code: ")` on `line 68` with `os.getenv("BLUETOOTH_PIN_CODE", "0000")`. The process isn't connected to any `tty`s, so there is no one on the line who can type in a PIN code. (:

Beside all these, there is no change in behavior of my Raspberry Pi 2; though, setting `capability` to `DisplayOnly` can have a positive effect on devices with built-in Bluetooth and cause them to ask for a PIN code while pairing.

**Comment by barhun** [comment]
@chrisys Setting `capability` to `DisplayOnly` must have an effect on how agents process pairing requests. May you, please, test this with one of your devices again?

**Comment by AlexProgrammerDE** [comment]
@barhun this is good. But why did you change some lines in bluetooth-udev and start.sh? We are concentrating on the agent and not at the bluetooth-udev and start.sh files. If you are requesting changes you can make a new PR. I changed the lines you said to the requested changes and i hope @shaunmulligan and @xginn8 will make also make tests. If someone of them wants to test it without your maybe unwanted changes can build it at my fork at: https://github.com/AlexProgrammerDE/balena-sound . I hope we will get good results. :smiley:.

**Comment by chrisys** [comment]
@AlexProgrammerDE I've just tried your branch, the pairing process now displays a 6-digit code on my phone (which is not the one I set in `BLUETOOTH_PIN_CODE`), and doesn't pair. See screenshot below:

Screenshot 2019-10-10 at 15 22 29

I've tested @barhun's changes in this PR, and the device again displays a random pin code which is not the one set in the environment variable, but then connects anyway.

Ultimately we need the user to *enter* the PIN code on their phone/laptop rather than having it shown to them to accept, otherwise it isn't going to prevent any unauthorised access.

**Comment by AlexProgrammerDE** [comment]
It is a good beginnig. I will now work on it in my fork. I will tell you when i am finished.

**Comment by AlexProgrammerDE** [comment]
So. I am thinking after your answer that the page was wrong with:

DisplayOnly or DisplayYesNo : authentication by PIN/passkey code
KeyboardOnly or KeyboardDisplay : yes/no choice to the pairing attempt
NoInputNoOutput : no user confirmation

It seems like DisplayOnly just displays you the passkey.
In my fork i am now set the capability to KeyboardDisplay. Maybe it works then.
You can try it now again in my fork at: https://github.com/AlexProgrammerDE/balena-sound

**Comment by AlexProgrammerDE** [comment]
Nice idea. If no password is set no Authentication is needed.  :+1: . And what is with the modification at the udev and start.sh?

**Comment by AlexProgrammerDE** [comment]
@chrisys is it the same output?

**Comment by AlexProgrammerDE** [comment]
I found maybe a solution for this problem: https://manpages.debian.org/jessie/bluez-tools/bt-agent.1.en.html It seems perfect i will try to integrate it.

**Comment by barhun** [comment]
Thanks for your efforts. My Raspberry Pi 2 offers, from the very beginning, the functionality we're trying to implement here; so it would be nice to see others test this on their devices with built-in Bluetooth. (:

**Comment by AlexProgrammerDE** [comment]
@barhun Thanks.

**Comment by AlexProgrammerDE** [comment]
@barhun @chrisys how should the authentification look like when the Pin variable is not set? Should we accept every pin, should we accept only 0000 or should we use no authentification? The first two are the easyest. When we take the third could appear extra agent problems.

**Comment by AlexProgrammerDE** [comment]
Maybe could work also the third option but i can't promise that it will work.
When I run bt-agent -d -c NoInputNoOutput should it maybe work without authentification.

**Comment by AlexProgrammerDE** [comment]
@chrisys you can test now my version with bt-agent from bluez. I hope it will work this time. I wrote it so that no authentication is needed when BLUETOOTH_PIN_CODE is not set. Please tell me the output of the cloud the authentication process and what errors occurred. My fork is at: https://github.com/AlexProgrammerDE/balena-sound

**Comment by AlexProgrammerDE** [comment]
@barhun i had a idea. We can commit your work in a separate branch for RPI 2 's with a adapter. And I am working on a version for all other in another PR. Then can we say you createded a solution for RPI 2 's and we are working on one for all other RPI 's.

**Comment by AlexProgrammerDE** [comment]
@chrisys 
> @AlexProgrammerDE @barhun can you test these changes using the on-board bluetooth on a Pi Zero, Pi 3 or Pi 4? I've just tried it again with an iPhone on iOS 13 and it's still generating random 6-digit codes and asking to confirm them on the balenaSound device. @barhun's PR pairs if you accept the pin-code and @AlexProgrammerDE your fork doesn't connect at all.
> 
> We need the user to be requested to enter the code defined in the env var on their phone/laptop, otherwise we haven't actually introduced any security here.

I thinked over it maybe are the capability's not only for the connecting device. Maybe are the capability for asking on the pi for the pin or the yes/no question. NoInputNoOutput seems to be the right. If bt-agent tool from bluez-uttils works it should be able to replace the bluetooth-agent file.

**Comment by barhun** [comment]
> @barhun i had a idea. We can commit your work in a separate branch for RPI 2 's with a adapter. And I am working on a version for all other in another PR. Then can we say you createded a solution for RPI 2 's and we are working on one for all other RPI 's.

@AlexProgrammerDE I think my PR can be closed/rejected if you are able to implement a solution which works for all kind of devices. By the way, in case anyone needs this kind of information, the output of `hciconfig hci0 -a` is as follows on my Pi 2:

image

**Comment by AlexProgrammerDE** [comment]
I have good news. I was able to create a code which implements a pin code request. I checked it out on a RPI 3 and it seemed to work great. I will now test it and check the stability of it. (By the way is it a Major change when I make the bluetooth-agent file uselles and make the agent through the bt-agent tool?)

**Comment by AlexProgrammerDE** [comment]
@barhun you can use the pin code option even if the PR of me is merged. I tested it on my RPI 2 with a Bluetooth Dongle and it worked like on the RPI 3. But i have a little job for you if you have nothing to do. It worked great on my Samsung Galaxy S9, but it don't wanted to pair on a Samsung Galaxy Tab A even if i used the correct pin code. So could it be nice and helpful when you try it on your devices.

**Comment by barhun** [comment]
@AlexProgrammerDE First of all, congrats! (: Now, we seem to have a solution that works for all devices and my PR can be closed/rejected. I think I can test it tomorrow in my free time and will let you know the result.

**Comment by AlexProgrammerDE** [comment]
Thanks. :smile:

**Comment by barhun** [comment]
hey, @AlexProgrammerDE; I've just tested your PR #48 and it works great! I'm now closing this PR, so we can move on with yours.

**Comment by AlexProgrammerDE** [comment]
Ok
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 18.10.19, 15:16, Burhan Del Rey <notifications@github.com> schrieb:
hey, @AlexProgrammerDE; I've just tested your PR #48 and it works great! I'm now closing this PR, so we can move on with yours.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/balena-io-projects/balena-sound/pull/35?email_source=notifications\u0026email_token=AJXH6TAKMMUEP5MSZCLB4D3QPGZL7A5CNFSM4I5Z2NJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBUM6XA#issuecomment-543739740",
"url": "https://github.com/balena-io-projects/balena-sound/pull/35?email_source=notifications\u0026email_token=AJXH6TAKMMUEP5MSZCLB4D3QPGZL7A5CNFSM4I5Z2NJ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBUM6XA#issuecomment-543739740",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request closed without merging**
