### PR TITLE
Suggestion extra instructions

### PR DESCRIPTION
**Pull request by Xyala**
Maybe some additional info useful for some of the more beginner folks.

### CODE REVIEW

**Comment by chrisys** [comment]
@Xyala I totally agree, thank you for your contribution! 

Before our CI will accept this, one of your commits needs to contain the following, I hope you don't mind updating:
```
Change-type: patch
Signed-off-by: Timothee Pineau <your@email.com>
```

**Comment by Xyala** [comment]
> @Xyala I totally agree, thank you for your contribution!
> 
> Before our CI will accept this, one of your commits needs to contain the following, I hope you don't mind updating:
> 
> ```
> Change-type: patch
> Signed-off-by: Timothee Pineau <your@email.com>
> ```

My pleasure. 
Sure - give me a sec, need to re-open things ...

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
Hey @Xyala I'm trying to get this merged but there's another issue - sorry for the trouble! In your first commit the line `Suggestion: ...` is being interpreted as a footer. I think if you just remove the colon character it will be fine. You can do this with `git rebase -i HEAD~3` and mark this one as reword.

**Comment by Xyala** [comment]
> Hey @Xyala I'm trying to get this merged but there's another issue - sorry for the trouble! In your first commit the line `Suggestion: ...` is being interpreted as a footer. I think if you just remove the colon character it will be fine. You can do this with `git rebase -i HEAD~3` and mark this one as reword.

@chrisys  let me know if i've done this correctly :)

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@Xyala perfect!

**Comment by Xyala** [comment]
Awesome, thanks!

**Pull request merged**
