### PR TITLE
Set system volume to provided value in bluetooth-udev

### PR DESCRIPTION
**Pull request by barhun**
This one fixes a minor bug in bluetooth-udev which sets the system volume to 100% all the time.

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
What are you providing with this PR?

**Comment by AlexProgrammerDE** [comment]
Please read https://github.com/balena-io-projects/balena-sound/blob/master/CONTRIBUTING.md

**Comment by chrisys** [comment]
@barhun this looks great - good catch. As Alex mentioned though, check the contribution guidelines to format your commit message, then we can merge 👍

**Comment by AlexProgrammerDE** [comment]
Have you a terminal?

**Comment by AlexProgrammerDE** [comment]
So now you ruined it. The CI of balena will now not accept your commits.  My way in this situation was that i backuped my edited files (In your case ONLY start.sh and bluetooth-udev) deleted my fork maked a new fork commited the backuped files in only ONE commit and dont forget do write in the description of this one commit:

ChangeType: minor

And then you need to close this PR and open a new. But then make please nothing on your fork.

**Comment by barhun** [comment]
Hahaha, sorry, my bad! Having a busy day. (: 'll send a new PR asap.

**Pull request closed without merging**
